import type { Metadata } from 'next'
import { Roboto_Mono } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import { GlobalProvider, ProfileSync } from '@/providers'
import { QueryClientProviderWrapper } from '@/providers'
import { ModalProvider } from '@/providers'
import { Bounce, ToastContainer } from 'react-toastify'

const roboto = Roboto_Mono({
  variable: '--font-roboto-mono',
  subsets: ['latin']
})
export const metadata: Metadata = {
  title: 'Chrono',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark
      }}
    >
      <html lang='en' suppressHydrationWarning>
        <body
          className={`${roboto.variable} ${roboto.className} max-w-desktop bg-bg-primary mx-auto min-h-screen w-full antialiased`}
        >
          <main className='relative h-full w-full'>
            <QueryClientProviderWrapper>
              <ModalProvider>
                <GlobalProvider>{children}</GlobalProvider>
                <ProfileSync />
              </ModalProvider>
              <ToastContainer
                position='top-right'
                autoClose={2000}
                hideProgressBar
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme='dark'
                transition={Bounce}
              />
            </QueryClientProviderWrapper>
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}
