import type { Metadata } from 'next'
import { Roboto_Mono } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import { GlobalProvider, ProfileSync } from '@/providers'
import { QueryClientProviderWrapper } from '@/providers'
import { ModalProvider } from '@/providers'
import { Toaster } from 'sonner'

const roboto = Roboto_Mono({
  variable: '--font-roboto-mono',
  subsets: ['latin']
})
export const metadata: Metadata = {
  title: 'Chrono',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark
      }}
    >
      <html lang='en' suppressHydrationWarning>
        <body
          className={`${roboto.variable} ${roboto.className} mx-auto min-h-screen w-full max-w-desktop bg-bg-primary antialiased`}
        >
          <main className='relative h-full w-full'>
            <QueryClientProviderWrapper>
              <ModalProvider>
                <GlobalProvider>{children}</GlobalProvider>
                <ProfileSync />
              </ModalProvider>
              <Toaster richColors />
            </QueryClientProviderWrapper>
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}
